workaround snakemake-interface-common/argparse-dataclas bug
This is the symptom:

    AttributeError: 'Namespace' object has no attribute 'storage_rucio_path_rewriting'

The no_path_rewriting argument is created when default=True instead of
storage_rucio_no_path_rewriting or similar.